# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Subin, Cho.
baseurl:        ""
url:            "http://www.Sweebinee.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Jihye Leee
  url:          http://Sweebinee.com/
  email:        subin.cho@i.ewha.ac.kr  
  github:       Sweebinee
  twitter:      playpingpong

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/sweebinee/sweebinee.github.io