# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Subin, Cho.
baseurl:        ""
url:            "https://sweebinee.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         subin
  url:          https://sweebinee.github.io
  email:        subin.cho@i.ewha.ac.kr  
  github:       Sweebinee
  twitter:      

# Custom vars
version:        1.0.0
github:
  repo:         https://github.com/sweebinee/sweebinee.github.io

  # if you don't want comments in your posts, leave categories empty
disqus:
  shortname: sweebinee-github-io # enter this from your disqus account

